.PHONY: typeset

typeset:
	pandoc                          \
	  --from         markdown       \
	  --to           latex          \
	  --template     template.tex   \
	  --out          EE452Assignment1Report.pdf \
	  --latex-engine   xelatex        \
	  Assignment1.md
